modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0"
issueTrackerURL = "https://github.com/MayaqqDev/Estrogen/issues"
[[mods]]
modId = "estrogen"
version = "${version}-forge"
displayName = "Create: Estrogen"
logoFile = "assets/estrogen/icon.png"
credits = "https://github.com/MayaqqDev/Estrogen/wiki/Credits"
authors = "Mayaqq"

# Description
description = '''
Create Addon Based around expressing yourself, fluid handling and expanding your factory. This mod adds a lot of new Items, Blocks, Mechanics and more!

Wiki: https://github.com/MayaqqDev/Estrogen/wiki
Discord: https://discord.gg/hue
Ko-fi: https://ko-fi.com/mayaqq
'''

[modproperties.estrogen]
'resourcefullib:resourcepack' = [
    { name="estrogenprogrammerart", description="Estrogen Programmer Art" }
]

# forge
[[dependencies.estrogen]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
# BEFORE, AFTER or NONE
ordering = "NONE"
# BOTH, CLIENT or SERVER
side = "BOTH"
# minecraft
[[dependencies.estrogen]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"
# create
[[dependencies.estrogen]]
modId = "create"
mandatory = true
versionRange = "[0.5.1.e,)"
ordering = "NONE"
side = "BOTH"
# curios
[[dependencies.estrogen]]
modId = "curios"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
# botarium
[[dependencies.estrogen]]
modId = "botarium"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
# resourceful lib
[[dependencies.estrogen]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.28,)"
ordering = "NONE"
side = "BOTH"